### ISSUE TITLE
Detected as malware by Malwarebytes 

### ISSUE THREAD

**Issue by Carl-Be** [gavinkendall/autoscreen#4]
Malwarebytes detected this software as a Real Time Transport Protocol attack.

**Comment by Carl-Be** [comment]
After further investigation indicates a false positive on Malwarebytes end. Suggestion: contact their support staff to get this resolved.

**Comment by gavinkendall** [comment]
I think it's because I'm using function calls from user32.dll to take screenshots which some anti-virus software detects such behaviour as being "bad" and these silly reports have been popping up in recent years despite the fact that my code was first published on SourceForge back in 2008. If anyone is concerned please feel free to review the code in https://github.com/gavinkendall/autoscreen/blob/master/ScreenCapture.cs

**Comment by chrismaliszewski** [comment]
Same problem reported when downloading via Chrome & Chromium Edge, 
![image](https://user-images.githubusercontent.com/7532602/114625771-ddb62b00-9d06-11eb-8592-c42a9e29756a.png)
https://www.virustotal.com/gui/file/2664548acfe4cdb2c113ee642edd92ba81ba0e907be3cff6c85e9712d6e08ca2/detection

**Comment by gavinkendall** [comment]
Microsoft Defender SmartScreen works on a reputation system and, since my application isn't signed with an expensive developer license and isn't popular, this warning will always appear. I'm not a verified software publisher; just a guy who writes code.

The only way to get around it is if I spend money on a developer license, become a verified publisher, and have thousands of downloads to increase positive reputation with the SmartScreen reputation system.

I've self-signed my application with a certificate to hopefully keep anti-virus software happy, but I think that SmartScreen prompt is just going to continue being an annoying issue unfortunately.

I'll ask other open source developers for any suggestions.
