### ISSUE TITLE
How to prevent autoscreen to be terminated in task manager?

### ISSUE THREAD

**Issue by hopeday6688** [gavinkendall/autoscreen#7]
Thanks Gavinkendall for the best tool that I could find !

I am a father of a 12 years old boy.  I use autoscreen to monitor what my boy does in his computor. When I login his computer as a normal user, I start autoscreen as administrator(UAC)，then autoscreen captures  his screen automatically in the background. The screenshots let me know what he has done in the computer. So autoscreen is very helpful for me. 

The passphrase param is  very useful, When I start autoscreen with a passphrase, my son can`t close the application manually, because he doesn`t know the passphrase.  But I find I can terminate the autoscreen process in task manager easily without the passphrase I set. It would be perfect if there is a method  which  can prevent autoscreen to be terminated in task manager.

**Comment by gavinkendall** [comment]
I agree. There was a trick you could do back in the days of Windows XP where you could hijack the Task Manager window and simply refresh it very quickly while not showing your application's process in the list, but that was fixed in Windows Vista and I haven't done any research into it since. I'm sure there's a way.

**Comment by formlessdao** [comment]
> I agree. There was a trick you could do back in the days of Windows XP where you could hijack the Task Manager window and simply refresh it very quickly while not showing your application's process in the list, but that was fixed in Windows Vista and I haven't done any research into it since. I'm sure there's a way.

Hi Gavin. would you be willing please to make your apps available on Linux and if not natively at least by using Wine?

**Comment by gavinkendall** [comment]
I haven't thought much about doing a Linux port because I have a feeling the same functionality could be achieved with a simple Python script. Auto Screen Capture might work with Wine but I haven't tried it yet. I've seen ShareX work with Wine and they're using the same Win32 screen capture methods as I am so I wouldn't be surprised if Auto Screen Capture also works with Wine.
